run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  # skip download modules
  modules-download-mode: readonly

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

linters-settings:
  forbidigo:
    forbid:
      - 'fmt\.Print.*'
  funlen:
    lines: 140
  lll:
    line-length: 140
  gosimple:
    go: "1.19"
    checks: ["all"]
  stylecheck:
    go: "1.19"
    checks: ["all"]
  unused:
    go: "1.19"
    checks: ["all"]
  staticcheck:
    go: "1.19"
    checks: ["all"]
  gci:
    sections:
      - standard
      - default
      - prefix(jcalendar)
  gofmt:
    simplify: true
  gocognit:
    min-complexity: 45

linters:
  enable:
    - forbidigo
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - bodyclose
    - revive
    - stylecheck
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - gofmt
    - depguard
    - misspell
    - lll
    - dogsled
    - nakedret
    - prealloc
    - exportloopref
    - gocritic
    - funlen
    - whitespace
    - errorlint
    - tparallel
    - nilerr
    - staticcheck
    - durationcheck
    - gci
    - gochecknoinits
    - gocognit

issues:
  exclude:
     - Using the variable on range scope `tt` in function literal
