// Package jcalendar provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package jcalendar

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Status *int    `json:"Status,omitempty"`
	Title  *string `json:"Title,omitempty"`
}

// InputUser defines model for InputUser.
type InputUser struct {
	Email          *string `json:"Email,omitempty"`
	FirstName      *string `json:"FirstName,omitempty"`
	LastName       *string `json:"LastName,omitempty"`
	TimeZoneOffset *int    `json:"TimeZoneOffset,omitempty"`
}

// OkResponse defines model for OkResponse.
type OkResponse = map[string]interface{}

// OutputUser defines model for OutputUser.
type OutputUser struct {
	CreateAt       *string `json:"CreateAt,omitempty"`
	Email          *string `json:"Email,omitempty"`
	FirstName      *string `json:"FirstName,omitempty"`
	ID             *int    `json:"ID,omitempty"`
	LastName       *string `json:"LastName,omitempty"`
	TimeZoneOffset *int    `json:"TimeZoneOffset,omitempty"`
	UpdateAt       *string `json:"UpdateAt,omitempty"`
}

// UserReponse defines model for UserReponse.
type UserReponse struct {
	Data *OutputUser `json:"data,omitempty"`
}

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody = InputUser

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = PostUsersJSONBody
